feature: persist data for CA and couchdb
hyperledger-labs/minifabric pull request #153
Opened 2021-02-05 09:34 UTC by itaru2622

This PR has following feature:
- persists CA data always
- persists couchdb data when minifab -s couchdb called

because current latest master persists data for peers and orderers but not for aboves...

2021-02-05 12:59 UTC, itaru2622 commented
CI test error was raised at channel creation phase. it is happenend after my code passed. please run CI test again to double check if the error was caused by accident or my fault.

2021-02-05 13:40 UTC, litong01 requested changes

2021-02-05 13:40 UTC, litong01 commented on playbooks/ops/netup/apply.yaml
> +    - "{{ allpeers + allorderers + allcas }}"
Can you change this to the following:

```
   - "{{ (DB_TYPE == couchdb) | ternary(allpeers+allorderers+allcas+allcouchdbs, allpeers+allorderers+allcas) }}"
```
Then remove next section.

2021-02-05 13:41 UTC, litong01 commented
@itaru2622 please address the comment and make sure that you have just one commit by using --amend, that way, the new push to your own repo will trigger the build again.

2021-02-05 15:04 UTC, itaru2622 commented
@litong01 thank you for your review. I applied your comment. please check it again.

2021-02-05 15:24 UTC, itaru2622 commented on playbooks/ops/netup/apply.yaml
> +    - "{{ allpeers + allorderers + allcas }}"
I applied your review at e3bb82f and push it.

2021-02-05 15:42 UTC, itaru2622 commented
hmm CI test failed again under exactly the same condition ( failed channel creation phase for minifab -i 1.4.1 but other tests passed).  I will send another trigger later if you need.

2021-02-06 01:06 UTC, itaru2622 commented
hmm CI test failed again at the same place by the  same reason ( channel creation phase at minifab up -i 1.4.1, by 'lookup orderer3.example.com: no such host')

I think it may be caused by CI test environment issue, since other versions tests(1.4.6..2.x) passed by CI test and my self test for version 1.4.1 passed as bellow:

```
# 
# myself test passed for minifab -i 1.4.1
# 
$ git log -1 --pretty=oneline
bc882f7b383fecaac10795405fd240b1a5e8a744 (HEAD -> persistdata_ca_couchdb, fork/persistdata_ca_couchdb) apply PR review comment.
$ docker build -t hyperledgerlabs/minifab:latest .
: 
$ ./minifab up -i 1.4.1
Using spec file: /mnt/minifabric/spec.yaml
Minifab Execution Context:
    FABRIC_RELEASE=1.4.1
    CHANNEL_NAME=mychannel
    PEER_DATABASE_TYPE=golevel
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=simple
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="init","a","200","b","300"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=false
    CURRENT_ORG=org0.example.com
    HOST_ADDRESSES=192.168.1.18
    WORKING_DIRECTORY: /mnt/minifabric
.....
:
# Current Minifabric image ID and created at date time ********
  3184fbd1c506   2021-02-05 14:40:41 +0000 UTC
.....
# Docker node status ******************************************
  a80955269d_cli : Up 7 seconds
  ca1.org1.example.com : Up 8 seconds
  ca1.org0.example.com : Up 9 seconds
  orderer3.example.com : Up 21 seconds
  orderer2.example.com : Up 21 seconds
  orderer1.example.com : Up 22 seconds
  peer2.org1.example.com : Up 23 seconds
  peer1.org1.example.com : Up 24 seconds
  peer2.org0.example.com : Up 25 seconds
  peer1.org0.example.com : Up 25 seconds

# Fabric network peer and orderer node health status **********
  peer1.org0.example.com "OK"
  peer2.org0.example.com "OK"
  peer1.org1.example.com "OK"
  peer2.org1.example.com "OK"
  orderer1.example.com "OK"
  orderer2.example.com "OK"
  orderer3.example.com "OK"
  Network Status: 100%

# Running operation: ******************************************
  channel create
:
# Discover endorsers results **********************************
  Chaincode endorsers file: ./vars/discover/mychannel/simple_endorsers.json
# Discover orderers results ***********************************
  Channel orderers file: ./vars/discover/mychannel/ordererendpoints.json

# STATS *******************************************************
minifab: ok=510	failed=0	

real	7m43.253s
user	3m7.384s
sys	0m35.922s
```
```
# 
# CI test triggered by PR failed.
#
./minifab up -i 1.4.1
:
# Running operation: ******************************************
  channel create
# Run the channel creation script on cli container ************
  non-zero return code
  2021-02-06 00:26:16.107 UTC [common.tools.configtxgen] main -> INFO 001 Loading configuration
  2021-02-06 00:26:16.136 UTC [common.tools.configtxgen.localconfig] Load -> INFO 002 Loaded configuration: /vars/configtx.yaml
  2021-02-06 00:26:16.160 UTC [common.tools.configtxgen.localconfig] completeInitialization -> INFO 003 orderer type: etcdraft
  2021-02-06 00:26:16.161 UTC [common.tools.configtxgen.localconfig] completeInitialization -> INFO 004 Orderer.EtcdRaft.Options unset, setting to tick_interval:"500ms" election_tick:10 heartbeat_tick:1 max_inflight_blocks:5 snapshot_interval_size:20971520 
  2021-02-06 00:26:16.161 UTC [common.tools.configtxgen.localconfig] LoadTopLevel -> INFO 005 Loaded configuration: /vars/configtx.yaml
  2021-02-06 00:26:16.161 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 006 Generating new channel configtx
  2021-02-06 00:26:16.162 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 007 Writing new channel tx
  Error: failed to create deliver client: orderer client failed to connect to orderer3.example.com:7050: failed to create new connection: connection error: desc = "transport: error while dialing: dial tcp: lookup orderer3.example.com: no such host"

Error: failed to create deliver client: orderer client failed to connect to orderer3.example.com:7050: failed to create new connection: connection error: desc = "transport: error while dialing: dial tcp: lookup orderer3.example.com: no such host"
```

2021-02-06 01:55 UTC, litong01 commented
This is really weird. I do not know what could cause the issue. Each time azure will allocate a new vm to test.

2021-02-06 01:56 UTC, litong01 commented
I know sometimes it fails when the nodes are not quite ready for requests, it will fail.

2021-02-06 04:04 UTC, itaru2622 commented
another shot also failed...orz

2021-02-06 11:28 UTC, litong01 commented on playbooks/ops/netup/apply.yaml
> +    - "{{ allpeers + allorderers + allcas }}"
please make sure you only have one commit in a PR. This is not related to the issue we have during the build but it is a courtesy in the community that you should not have multiple commits in a PR, so reviewing the PR becomes difficult.

2021-02-06 11:44 UTC, litong01 commented
I've tested the PR locally using 1.4.1 release, and things are working as expected. really not sure why it is failing on Azure. If you please make your PR into one commit, I will try to merge it.

2021-02-06 12:44 UTC, itaru2622 commented
PR 156 is good news, for me. I will push again after PR 156 merged.

2021-02-06 13:19 UTC, itaru2622 commented
@litong01 I rebased my PR and now it has just one commit.

2021-02-06 13:49 UTC, litong01 commented
let's wait for this PR https://github.com/hyperledger-labs/minifabric/pull/156 to get merged, then we will trigger this again.

2021-02-06 16:30 UTC, litong01 approved these changes
Thanks

2021-02-06 16:30 UTC, merged