improving on-premise k8s uses.
hyperledger-labs/minifabric pull request #235
Opened 2021-07-15 05:53 UTC by itaru2622

* supporting local-path-provisioner, for persistent storage.
  local-path-provisioner seems not support 'subPath' for volumeMounts.

2021-07-19 10:11 UTC, itaru2622 commented
@litong01 could you review this PR, please.

2021-07-19 14:23 UTC, litong01 requested changes
I am not really sure why this is needed, can you explain why this is an improvement. Thanks.

2021-07-19 16:08 UTC, itaru2622 commented
@litong01 ok, I will explain it:

first, current minifabric uses persistent volumes, by use of "volumeMounts" in case of k8s environment.

on cloud managed k8s, each vendor provides its own dynamic persistent volume provisioner as its default service, like aws-ebs.  Those provisioner support subpath. so there are no problem in current code as far as managed k8s cases.

on the other hand, on-premise k8s, user needs to install open source dynamic persistent provisioner by himself to avoid specifying lots of PV and PVC entries in his k8s.

local-path-provisioner (https://github.com/rancher/local-path-provisioner ) is one of open source dynamic persistent volume provisioner. It is widely used by many onpremise k8s, because of config-less and easy use.
but unfortunately local-path-provisioner  seems not supporting 'subpath'.
So, at this moment,  user has to find out alternatives ( such as NFS based provisioner and configuring it), or give up using minifabric.

when I delete 'subpath' keyword and changed as this PR, minifabric could work with local-path-provisioner.
It's a small change in the code, but it's very kind to on-premises k8s users. That's the reason I post this PR.

2021-07-19 16:42 UTC, litong01 commented
@itaru2622 I understand the need for different storage cases. It seems to me that the PR is hard coded this and there seems no configurable parameters to indicate use or not use this feature.

2021-07-19 17:04 UTC, itaru2622 commented
@litong01 even after current code merged as it is, user can still use any type of storage class as user wishes, including aws-ebs in managed k8s case. so, I think there is no need configurable parameter. why you perfer to involve such parameter?

2021-07-19 20:25 UTC, litong01 commented
@itaru2622 the proposed PR will always create a volume sized to be 100Mi, and mounted to where the blockchain data will be saved, I am not seeing that as an optional thing. it will always do that, correct? I do not think every one will be happy that the data is restricted to be 100Mi, am I missing something here?

2021-07-19 21:09 UTC, itaru2622 commented
@litong01 you are misunderstanding my PR, I think.

It creates 5Gi data volume and 100Mi volumes for msp and tmp(/dataroot) folder.

/var/hyperledger/production is {{nodename}}-data and its storage is 5Gi.

100Mi for msp folder is enough, I think.
If you want more for msp and tmp, I will change their size to 1Gi.

2021-07-20 11:42 UTC, litong01 approved these changes
Thanks

2021-07-20 11:42 UTC, merged